#import "notes_template.typ": template, Rec, Rat, exercise
#show: template.with(
  sheet: 2
)

#exercise()
Given monoids $M, M'$, and $N$, and a monoid homomorphism $h : M times M' -> N$, prove that the mappings $f : M -> N, g : M' -> N$, and $h' : M times M' -> N times N$, which are given by
$
f(m) = h(m,1) quad g(m') = h(1,m') quad h'(m,m') = (f(m),g(m'))
$
for all $m in M$ and $m' in M'$, are again monoid homomorphisms.

#text(blue)[
  We start with $f$. Obviously, $f(1) = h(1,1) = 1$ and
  $
  f(m_1 dot.c m_2) = h(m_1 dot.c m_2, 1 dot.c 1) = h(m_1,1) dot.c h(m_2,1) = f(m_1) dot.c f(m_2)
  $
  for all $m_1,m_2 in M$, which proves that $f$ is a monoid homomorphism. The proof for $g$ is entirely analogous. Finally $h'(1,1) = (f(1),g(1)) = (1,1)$ and
  $
  h'((m_1,m'_1) times (m_2,m'_2)) &= h'(m_1 dot.c m_2, m'_1 dot.c m'_2) = (f(m_1 dot.c m_2), g(m'_1 dot.c m'_2)) \
  &= (f(m_1) dot.c f(m_2), g(m'_1) dot.c g(m'_2)) \
  &= (f(m_1), g(m'_1)) times (f(m_2), g(m'_2)) \
  &= h'(m_1, m'_1) times h'(m_2, m'_2)
  $
]

#exercise()
Let $A$ be an alphabet and $A^plus.circle = (NN^A, union, emptyset)$ be free the commutative monoid generated by A #text(gray)[(multisets over $A$ with union $union$ and the empty set $emptyset$; formally, a multiset over $A$ is a mapping $S : A -> NN$, the union $S union T$ of multisets $S,T : A -> NN$ is given by $(S union T)(a) = S(a) + T(a)$ for all $a in A$, and the empty multiset is the mapping $emptyset : A -> NN$ given by $emptyset (a) = 0$ for all $a in A$; roughly speaking, a multiset is a set counting multiplicities of the contained elements of a list without order)]. Prove that $L in Rat(A^plus.circle)$ if and only if it is semilinear; i.e., a finite union of sets of the form
$
x y_1^* y_2^* dots.h.c y_n^* quad "with" n in NN, x, y_1, ... , y_n in NN^A.
$

#text(blue)[
  We first observe that $L^* = L^+ union {epsilon}$ for all $L subset.eq A^plus.circle$, so star and iteration closure are equivalent given the remaining closures of the rational sets. With these ovservations, the semilinear sets are obviously rational. For the converse, the empty set $emptyset$ (i.e., empty union) and the singletons ($x y^*_1 dots.c y^*_n$ for $n = 0$) are semilinear and the semilinear sets are closed under union. The product of two semilinear sets is certainly a finite union of products of the form
  $
  (x y^*_1 y^*_2 dots.c y^*_n) dot.c (x' z^*_1 z^*_2 dots.c z^*_m) quad "with" n,m in NN, x,x',y_1,dots,y_n,z_1,dots,z_m in A^plus.circle.
  $
  The latter product equates to $(x x')y^*_1 y^*_2 dots.c y^*_n z^*_1 z^*_2 dots.c z^*_m$, which shows that semilinear sets are closed under products. It remains to show that they are also closed under start. We first observe that $(L union M)^* = L^* M^*$ since the order is irrelevant. Additionally #box[$(x y^*_1 y^*_2 dots.c y^*_n) = x^* y^*_1 y^*_2 dots.c y^*_n$], which shows closure under star. Since rational sets are the smallest class with those closure properties, it follows that each ration set is semiliniear.
]

#exercise()
Demonstrate that, in general, the rational relations are not closed under intersection. \
_Hint:_ Investigate $Rat({a}^* times {b,c}^*)$.

#text(blue)[
  We consider the relations
  $
  R = {(epsilon,b)}^*{(a,c)}^* = {(a^k,b^l c^k) | l,k in NN}\
  S = {(a,b)}^*{(epsilon,c)}^* = {(a^k,b^k c^l) | l,k in NN}
  $
  and their intersection $R inter S = {(a^k,b^k c^k) | k in NN}$. Suppose that $R inter S$ is rational and consider the mapping $h : {a}^* times {b,c}^* -> {b,c}^*$ given by $h(u,v) = v$ for all $u in {a}^*$ and $v in {b,c}^*$. Then $h(epsilon, epsilon) = epsilon$ and
  $
  h((u,v) times.circle (u',v')) = h(u u', v v') = v v' = h(u,v)h(u',v')
  $
  for all $u,u' in {a}^*$ and $v,v' in {b,c}^*$, which shows that $h$ is a homomorphism. Consequently, $h(R inter S) = {b^k c^k | k in NN} in Rat({a,b}^*)$, which is a contradiction, so $R inter S$ cannot be rational.
]

#exercise()
Let $M$ be a group. Prove that $L^(-1) = {m^(-1) | m in L} in Rat(M)$ for all $L in Rat(M)$.

#text(blue)[
  Consider the set $cal(R)$ of set $L subset.eq M$ such that $L^(-1)$ is rational. Clearly $emptyset in cal(R)$ and ${m} in cal(R)$ for all $m in M$ because ${m}^(-1) = {m^(-1)}$ is a singleton. Moreover, $(U union V)^(-1) = U^(-1) union V^(-1)$ for all $U, V subset.eq M$, which proves closure under union. For the product, we observe that
  $
  (U V)^(-1) = {(u v)^(-1) | u in U, v in V} = {v^(-1)u^(-1) | u in U, v in V} = V^(-1) U^(-1)
  $
  which proves closure under product. Finally,
  $
  (U^*)^(-1) &= {(u_1 dots.c u_n)^(-1) | n in NN, u_1, dots, u_n in U} \
             &= {(u_n^(-1) dots.c u_1^(-1)) | n in NN, u_1, dots, u_n in U} \
             &= {(v_1 dots.c v_n | n in NN, v_1, dots, v_n in U^(-1)} = (U^(-1))^*
  $
  which proves closure under star. Consequently, $cal(R)$ contains all rational sets, so $L^(-1)$ is rational for all rational $L subset.eq M$.
]
